auto: true

markdown: kramdown
pygments: true
paginate: 8
permalink: /:title

title: NatsuZone.com
url: http://www.natsuzone.com
feed: /atom.xml
author_info: <a href="http://www.natsuzone.com/">Natsu</a>

comments :
provider : duoshuo
duoshuo :
shortname : natsu
