auto: true

markdown: kramdown
pygments: true
paginate: 8
permalink: /:title
highlighter: rouge

title: NatsuZone.com
url: http://moenatsu.github.io/
feed: /atom.xml
author_info: <a href="http://moenatsu.github.io/">Natsu</a>

comments :
provider : duoshuo
duoshuo :
shortname : natsu
